#!/usr/bin/env node
/**
 * clinerules-mcp — On-demand .clinerules lookup MCP
 * =================================================
 *
 * Replaces loading all 118 .clinerules into every Cline task's system prompt
 * (~972KB / ~243K tokens, ~$3.65/task at Opus pricing). With this MCP +
 * a fail-safe _INDEX.md, Cline fetches rules on demand via clinerules_lookup.
 *
 * Architecture: stdio MCP wrapped by supergateway → streamableHttp on port 7860.
 * Source of truth: ~/Documents/Cline/Rules/*.md (untouched).
 * Index: SQLite + FTS5 at ~/.clinerules-mcp/index.sqlite (rebuilt on startup).
 *
 * Phase 1 tools shipped here:
 *   - clinerules_lookup(rule_id | slug | filename)
 *   - clinerules_search(query, limit?)
 *   - clinerules_list_by_topic(topic)
 *   - clinerules_record_violation(rule_id, task_id, evidence)
 *   - clinerules_reindex()
 *
 * Per orchestrator_idea #5344 (P0, approved).
 */

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { z } from "zod";
import Database from "better-sqlite3";
import * as fs from "fs";
import * as path from "path";
import * as os from "os";

// ─── Configuration ──────────────────────────────────────────────────────────
const HOME = os.homedir();
const RULES_DIR = path.join(HOME, "Documents/Cline/Rules");
// Phase 3 shrinkage (orchestrator_idea TBD): non-hardfloor rules live here
// so Cline's hardcoded recursive walk of RULES_DIR no longer injects them.
// MCP still indexes both directories so clinerules_lookup/search work unchanged.
const ARCHIVE_DIR = path.join(HOME, "Documents/Cline/Rules-archive");
const DB_DIR = process.env.CLINERULES_DB_DIR || path.join(HOME, ".clinerules-mcp");
const DB_PATH = process.env.CLINERULES_DB_PATH || path.join(DB_DIR, "index.sqlite");
const VERSION = "0.1.0";

if (!fs.existsSync(DB_DIR)) fs.mkdirSync(DB_DIR, { recursive: true });

// ─── Index builder ──────────────────────────────────────────────────────────

interface RuleRow {
  rule_id: string;       // numeric id from filename prefix ("00", "29", "100", etc)
  slug: string;          // filename without .md
  filename: string;      // full filename
  path: string;          // absolute path
  title: string;         // first H1 (or filename if absent)
  body: string;          // full file content
  size_bytes: number;
  size_tokens_est: number; // body chars / 4 (Opus-ish)
  cross_refs: string;    // JSON array of cited .clinerules/N
  last_updated: string;
  has_source_incident: number; // 1 if "## source" or "## last updated" or "source incident" found
  is_hardfloor: number;  // 1 if in HARDFLOOR_SET
  mtime: number;
}

// Hard-floor rules — always loaded into system prompt.
//
// idea #25151 (2026-08-08): this used to be a HARDCODED list, and it was one of FOUR
// copies of the same set that had to agree by hand (MCP registry / .pre-write-lint.sh
// G5+G6 gates / the actual Rules/ dir / _router_core.py steering). The 2026-07-25 floor
// trim updated only some of them, so the MCP named 9 rules while 20 were on disk. Rules
// 119/120/143/144/259/267/161/297/99-subagent were loaded into every window but reported
// as NOT hardfloor, so nothing treated them as binding. It survived ~2 weeks undetected.
//
// The set is now DERIVED from the Rules/ directory listing via .hardfloor-manifest
// (regenerated by scripts/sync_hardfloor_manifest.sh). Adding or removing a rule file is
// the ONLY action needed — there is no second list to update, so this class of drift is
// structurally impossible rather than merely detectable.
//
// Fallback: if the manifest is missing/unreadable we derive directly from the directory,
// which is the same source of truth. We never fall back to a stale hardcoded list.
const MANIFEST_PATH = path.join(HOME, "Documents/Cline/Rules/.hardfloor-manifest");

// Always-loaded but navigational/auto-generated: not binding gates.
const META_SLUGS = new Set([
  "_INDEX",
  "_RULE_TREE",
  "EXECUTE_ORDER_66",
  "REQUIREMENT_IDEA_AUTO_FILE",
  "99-yolo-prevention-learned",
]);

function isMetaSlug(slug: string): boolean {
  return slug.startsWith("_") || META_SLUGS.has(slug);
}

function loadHardfloorManifest(): Set<string> {
  // Preferred: read the generated manifest.
  try {
    const raw = fs.readFileSync(MANIFEST_PATH, "utf-8");
    const out = new Set<string>();
    let section = "";
    for (const line of raw.split("\n")) {
      const t = line.trim();
      if (!t || t.startsWith("#")) continue;
      if (t === "[hardfloor]" || t === "[meta]") { section = t; continue; }
      if (section === "[hardfloor]") out.add(t);
    }
    if (out.size > 0) return out;
  } catch { /* fall through to directory derivation */ }

  // Fallback: derive from the directory listing (same source of truth as the manifest).
  try {
    const out = new Set<string>();
    for (const f of fs.readdirSync(path.join(HOME, "Documents/Cline/Rules"))) {
      if (!f.endsWith(".md") || f.includes(".bak")) continue;
      const slug = f.replace(/\.md$/, "");
      if (!isMetaSlug(slug)) out.add(slug);
    }
    return out;
  } catch {
    return new Set<string>();
  }
}

const HARDFLOOR_SLUGS = loadHardfloorManifest();


function parseRuleId(filename: string): string {
  // "29-agents-act-on-confidence-tier.md" → "29"
  // "00-READ-FIRST-17-force-subagent-use..." → "00-READ-FIRST-17"
  // "EXECUTE_ORDER_66.md" → "EXECUTE_ORDER_66"
  const base = filename.replace(/\.md$/, "");
  const m = base.match(/^(\d+(?:-READ-FIRST-\d+)?)/);
  if (m) return m[1];
  return base;
}

function extractTitle(body: string, fallback: string): string {
  const m = body.match(/^#\s+(.+)$/m);
  return m ? m[1].trim() : fallback;
}

function extractCrossRefs(body: string): string[] {
  // Find ".clinerules/NN" or "rule NN" or "Rule NN"
  const refs = new Set<string>();
  const patterns = [
    /\.clinerules\/(\d+(?:-READ-FIRST-\d+)?)/gi,
    /\brule[s]?\s+(\d{1,3})\b/gi,
  ];
  for (const re of patterns) {
    let m: RegExpExecArray | null;
    while ((m = re.exec(body)) !== null) {
      refs.add(m[1]);
    }
  }
  return Array.from(refs).sort();
}

function hasSourceIncident(body: string): boolean {
  return /(?:source incident|## source|## last updated|^Source:)/im.test(body);
}

function initSchema(db: Database.Database): void {
  db.exec(`
    CREATE TABLE IF NOT EXISTS rules (
      rule_id TEXT NOT NULL,
      slug TEXT PRIMARY KEY,
      filename TEXT NOT NULL,
      path TEXT NOT NULL,
      title TEXT,
      body TEXT,
      size_bytes INTEGER,
      size_tokens_est INTEGER,
      cross_refs TEXT,
      last_updated TEXT,
      has_source_incident INTEGER DEFAULT 0,
      is_hardfloor INTEGER DEFAULT 0,
      mtime INTEGER
    );
    CREATE INDEX IF NOT EXISTS idx_rules_rule_id ON rules(rule_id);
    CREATE INDEX IF NOT EXISTS idx_rules_hardfloor ON rules(is_hardfloor);

    CREATE VIRTUAL TABLE IF NOT EXISTS rules_fts USING fts5(
      slug UNINDEXED,
      title,
      body,
      tokenize = 'porter unicode61'
    );

    CREATE TABLE IF NOT EXISTS violations (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      rule_id TEXT NOT NULL,
      task_id TEXT,
      evidence TEXT,
      recorded_at TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now'))
    );
    CREATE INDEX IF NOT EXISTS idx_violations_rule ON violations(rule_id);

    CREATE TABLE IF NOT EXISTS lookups (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      rule_id TEXT,
      slug TEXT,
      query TEXT,
      via TEXT,
      task_id TEXT,
      looked_up_at TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now'))
    );

    CREATE TABLE IF NOT EXISTS meta (
      k TEXT PRIMARY KEY,
      v TEXT
    );
  `);
}

function reindex(db: Database.Database, verbose = false): {
  count: number;
  total_bytes: number;
  total_tokens: number;
  hardfloor_count: number;
} {
  // Phase 3: index BOTH the live Rules/ (small — hardfloors only after shrinkage)
  // AND Rules-archive/ (the non-hardfloor majority that no longer auto-loads
  // into Cline's system prompt). MCP lookups still serve the full corpus.
  const collected: { full: string; filename: string }[] = [];
  const walk = (dir: string) => {
    if (!fs.existsSync(dir)) return;
    for (const f of fs.readdirSync(dir).sort()) {
      if (!f.endsWith(".md")) continue;
      collected.push({ full: path.join(dir, f), filename: f });
    }
  };
  walk(RULES_DIR);
  walk(ARCHIVE_DIR);

  // Dedupe by slug (Rules/ wins over Rules-archive/ if both have same file)
  const seen = new Set<string>();
  const files = collected.filter((c) => {
    const slug = c.filename.replace(/\.md$/, "");
    if (seen.has(slug)) return false;
    seen.add(slug);
    return true;
  });

  const tx = db.transaction(() => {
    db.exec(`DELETE FROM rules; DELETE FROM rules_fts;`);
    const ins = db.prepare(`
      INSERT INTO rules (
        rule_id, slug, filename, path, title, body,
        size_bytes, size_tokens_est, cross_refs, last_updated,
        has_source_incident, is_hardfloor, mtime
      ) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)
    `);
    const insFts = db.prepare(`INSERT INTO rules_fts (slug, title, body) VALUES (?,?,?)`);

    for (const { full, filename: f } of files) {
      const stat = fs.statSync(full);
      const body = fs.readFileSync(full, "utf-8");
      const slug = f.replace(/\.md$/, "");
      const rule_id = parseRuleId(f);
      const title = extractTitle(body, slug);
      const refs = extractCrossRefs(body);
      const sizeBytes = stat.size;
      const sizeTokens = Math.ceil(body.length / 4);
      const hasSrc = hasSourceIncident(body) ? 1 : 0;
      const isHf = HARDFLOOR_SLUGS.has(slug) ? 1 : 0;
      const lastUpdMatch = body.match(/##\s+(?:last\s+updated|Last\s+updated)\s*\n+\s*([\d-]+)/i);
      const lastUpd = lastUpdMatch ? lastUpdMatch[1] : "";

      ins.run(
        rule_id, slug, f, full, title, body,
        sizeBytes, sizeTokens, JSON.stringify(refs), lastUpd,
        hasSrc, isHf, Math.floor(stat.mtimeMs)
      );
      insFts.run(slug, title, body);
    }

    db.prepare(`INSERT OR REPLACE INTO meta (k,v) VALUES (?,?)`)
      .run("last_reindex", new Date().toISOString());
    db.prepare(`INSERT OR REPLACE INTO meta (k,v) VALUES (?,?)`)
      .run("last_reindex_ts", String(Date.now()));
    db.prepare(`INSERT OR REPLACE INTO meta (k,v) VALUES (?,?)`)
      .run("version", VERSION);
  });
  tx();

  // 2026-07-03 WAL-bloat fix: checkpoint immediately after the big write so
  // WAL frames fold into the main DB right away. Without this, 5 concurrent
  // processes each running this reindex every 5 min grew the WAL to 101 MB,
  // which stalled new-process init (WAL replay on open) → Cline auto-disable.
  try { db.pragma("wal_checkpoint(PASSIVE)"); } catch { /* non-fatal */ }

  const stats = db.prepare(`
    SELECT COUNT(*) AS n,
           COALESCE(SUM(size_bytes),0) AS total_bytes,
           COALESCE(SUM(size_tokens_est),0) AS total_tokens,
           COALESCE(SUM(is_hardfloor),0) AS hardfloor_count
    FROM rules
  `).get() as { n: number; total_bytes: number; total_tokens: number; hardfloor_count: number };

  if (verbose) {
    console.error(`[clinerules-mcp] reindexed ${stats.n} rules, ${stats.total_bytes} bytes, ~${stats.total_tokens} tokens, ${stats.hardfloor_count} hardfloor`);
  }

  return {
    count: stats.n,
    total_bytes: stats.total_bytes,
    total_tokens: stats.total_tokens,
    hardfloor_count: stats.hardfloor_count,
  };
}

// ─── Bootstrap ─────────────────────────────────────────────────────────────

// 2026-05-19 v3 fix: install error handlers BEFORE doing anything else.
// supergateway 3.4.3 stateless mode synthesizes one initialize per non-init
// request, which fills stdio buffers and triggers EPIPE/ECONNRESET in the
// child. Without these handlers the node child dies with "Pipe.onStreamRead"
// trace and Cline windows go yellow.
process.stdin.on("error", (e: any) => {
  console.error(`[clinerules-mcp] stdin error (swallowed): ${e?.code || e?.message}`);
});
process.stdout.on("error", (e: any) => {
  console.error(`[clinerules-mcp] stdout error (swallowed): ${e?.code || e?.message}`);
});
process.on("uncaughtException", (e: any) => {
  console.error(`[clinerules-mcp] uncaughtException (swallowed): ${e?.message || e}`);
});
process.on("unhandledRejection", (e: any) => {
  console.error(`[clinerules-mcp] unhandledRejection (swallowed): ${e?.message || e}`);
});

const db = new Database(DB_PATH);
db.pragma("journal_mode = WAL");
db.pragma("busy_timeout = 5000");      // wait up to 5s for locks instead of SQLITE_BUSY throw
db.pragma("wal_autocheckpoint = 500"); // checkpoint every ~2MB, not default ~4MB
initSchema(db);

// 2026-07-03: skip the expensive full reindex when no rule file changed.
// Returns true only if any .md in Rules/ or Rules-archive/ has mtime newer
// than the last reindex. Makes the 5-min background interval + 10s post-
// startup reindex a cheap stat-loop no-op 99% of the time, so concurrent
// windows don't pile write load on the shared SQLite WAL.
function needsReindex(): boolean {
  let newestMtime = 0;
  for (const dir of [RULES_DIR, ARCHIVE_DIR]) {
    if (!fs.existsSync(dir)) continue;
    for (const f of fs.readdirSync(dir)) {
      if (!f.endsWith(".md")) continue;
      try {
        const st = fs.statSync(path.join(dir, f));
        if (st.mtimeMs > newestMtime) newestMtime = st.mtimeMs;
      } catch { /* skip unreadable */ }
    }
  }
  const row = db.prepare(`SELECT v FROM meta WHERE k = 'last_reindex_ts'`).get() as { v?: string } | undefined;
  const lastTs = row?.v ? parseInt(row.v, 10) : 0;
  return newestMtime > lastTs;
}

// CLI mode: `node build/index.js --reindex-only`
if (process.argv.includes("--reindex-only")) {
  const stats = reindex(db, true);
  console.error(JSON.stringify({ ok: true, ...stats }, null, 2));
  process.exit(0);
}

// Phase 3 fix (2026-05-19): defer reindex until AFTER connect(), so the
// MCP child accepts incoming initialize requests from supergateway without
// the 200ms+ startup stall that piles up backlog from multiple Cline
// windows hammering port 7860. The first lookup will already have a
// cached index from any prior run; the deferred reindex catches new rules
// on a 50ms idle delay.
let stats: { count: number; total_bytes: number; total_tokens: number; hardfloor_count: number } = {
  count: 0, total_bytes: 0, total_tokens: 0, hardfloor_count: 0,
};

// ─── MCP server ────────────────────────────────────────────────────────────

const server = new McpServer({
  name: "clinerules-mcp",
  version: VERSION,
});

function logLookup(rule_id: string | null, slug: string | null, query: string | null, via: string, task_id?: string) {
  try {
    db.prepare(`INSERT INTO lookups (rule_id, slug, query, via, task_id) VALUES (?,?,?,?,?)`)
      .run(rule_id, slug, query, via, task_id || null);
  } catch { /* never fail a lookup on telemetry */ }
}

function violationCount(rule_id: string): number {
  const r = db.prepare(`SELECT COUNT(*) AS n FROM violations WHERE rule_id = ?`).get(rule_id) as { n: number };
  return r.n;
}

function findRule(query: string): RuleRow | null {
  const q = query.trim();
  // Try exact slug
  let r = db.prepare(`SELECT * FROM rules WHERE slug = ?`).get(q) as RuleRow | undefined;
  if (r) return r;
  // Try exact rule_id
  r = db.prepare(`SELECT * FROM rules WHERE rule_id = ?`).get(q) as RuleRow | undefined;
  if (r) return r;
  // Try numeric — strip leading zeros, then "%-" prefix match
  if (/^\d+$/.test(q)) {
    const n = parseInt(q, 10);
    const padded2 = n.toString().padStart(2, "0");
    r = db.prepare(`SELECT * FROM rules WHERE rule_id = ? OR slug LIKE ? OR slug LIKE ? LIMIT 1`)
      .get(n.toString(), `${padded2}-%`, `${n}-%`) as RuleRow | undefined;
    if (r) return r;
  }
  // Try filename
  r = db.prepare(`SELECT * FROM rules WHERE filename = ?`).get(q) as RuleRow | undefined;
  if (r) return r;
  // Try slug prefix (e.g. "29" → "29-agents-...")
  r = db.prepare(`SELECT * FROM rules WHERE slug LIKE ? ORDER BY slug LIMIT 1`)
    .get(`${q}%`) as RuleRow | undefined;
  if (r) return r;
  return null;
}

// ─── Tools ─────────────────────────────────────────────────────────────────

server.tool(
  "clinerules_lookup",
  "Fetch the full body of a single .clinerules file by rule_id, slug, or filename. Returns rule body + cross-refs + violation count. Use when you need the actual text of a specific rule (e.g. 'lookup rule 29').",
  {
    rule_id: z.string().describe("Rule ID, slug, or filename. Examples: '29', '29-agents-act-on-confidence-tier', 'EXECUTE_ORDER_66'."),
    task_id: z.string().optional().describe("Optional Cline task ID for audit telemetry."),
  },
  async ({ rule_id, task_id }) => {
    const row = findRule(rule_id);
    if (!row) {
      logLookup(null, null, rule_id, "lookup_miss", task_id);
      return {
        content: [{
          type: "text",
          text: `No rule found matching '${rule_id}'. Try clinerules_search('${rule_id}') or read ~/Documents/Cline/Rules/_INDEX.md.`,
        }],
      };
    }
    logLookup(row.rule_id, row.slug, rule_id, "lookup_hit", task_id);
    const vc = violationCount(row.rule_id);
    const refs = JSON.parse(row.cross_refs || "[]");
    const header = [
      `📖 Rule ${row.rule_id} — ${row.title}`,
      `Slug: ${row.slug}`,
      `Size: ${row.size_bytes} bytes (~${row.size_tokens_est} tokens) · Hardfloor: ${row.is_hardfloor ? "yes" : "no"} · Source incident: ${row.has_source_incident ? "yes" : "no"} · Violations recorded: ${vc}`,
      refs.length ? `Cross-refs: ${refs.map((r: string) => `.clinerules/${r}`).join(", ")}` : "Cross-refs: (none parsed)",
      "",
      "──── BODY ────",
      "",
    ].join("\n");
    return { content: [{ type: "text", text: header + row.body }] };
  }
);

server.tool(
  "clinerules_search",
  "Full-text search across all .clinerules bodies (FTS5 porter stemming). Use when you don't know the rule number — pass keywords like 'tunnel wedged' or 'refund autonomous'. Returns top-N matches with snippets.",
  {
    query: z.string().describe("Search query (keywords, phrases). FTS5 syntax supported."),
    limit: z.number().int().min(1).max(20).default(5).describe("Max results (default 5)."),
    task_id: z.string().optional().describe("Optional Cline task ID for audit telemetry."),
  },
  async ({ query, limit, task_id }) => {
    // Sanitize: FTS5 hates unmatched quotes and certain punctuation
    const safe = query.replace(/["']/g, " ").replace(/[^\w\s\-]/g, " ").trim();
    if (!safe) {
      return { content: [{ type: "text", text: `Empty/unsupported query: '${query}'.` }] };
    }
    let rows: any[];
    try {
      rows = db.prepare(`
        SELECT r.rule_id, r.slug, r.title, r.size_tokens_est, r.is_hardfloor,
               snippet(rules_fts, 2, '«', '»', '…', 24) AS snippet,
               bm25(rules_fts) AS score
        FROM rules_fts
        JOIN rules r ON r.slug = rules_fts.slug
        WHERE rules_fts MATCH ?
        ORDER BY score
        LIMIT ?
      `).all(safe, limit) as any[];
    } catch (e: any) {
      return { content: [{ type: "text", text: `Search error: ${e.message}. Try simpler keywords.` }] };
    }
    logLookup(null, null, query, "search", task_id);
    if (!rows.length) {
      return { content: [{ type: "text", text: `No matches for '${query}'. Browse ~/Documents/Cline/Rules/_INDEX.md.` }] };
    }
    const out = [`🔎 ${rows.length} match(es) for '${query}':`, ""];
    for (const r of rows) {
      out.push(`• Rule ${r.rule_id} — ${r.title}  (~${r.size_tokens_est} tokens${r.is_hardfloor ? ", hardfloor" : ""})`);
      out.push(`  slug: ${r.slug}`);
      out.push(`  ${r.snippet.replace(/\s+/g, " ").trim()}`);
      out.push("");
    }
    out.push("Use clinerules_lookup(rule_id='<id>') to fetch the full body.");
    return { content: [{ type: "text", text: out.join("\n") }] };
  }
);

server.tool(
  "clinerules_list_by_topic",
  "List rules matching a topic keyword with a 1-line summary each. Faster than search when you want to scan a domain (e.g. topic='subagent' → all rules about subagent dispatch).",
  {
    topic: z.string().describe("Topic keyword. Matches rule titles, slugs, and first 500 chars of body."),
    limit: z.number().int().min(1).max(50).default(15),
  },
  async ({ topic, limit }) => {
    const t = `%${topic.replace(/[%_]/g, "")}%`;
    const rows = db.prepare(`
      SELECT rule_id, slug, title, size_tokens_est, is_hardfloor,
             SUBSTR(body, 1, 200) AS preview
      FROM rules
      WHERE title LIKE ? OR slug LIKE ? OR SUBSTR(body, 1, 500) LIKE ?
      ORDER BY is_hardfloor DESC, CAST(rule_id AS INTEGER), slug
      LIMIT ?
    `).all(t, t, t, limit) as any[];
    if (!rows.length) {
      return { content: [{ type: "text", text: `No rules matching topic '${topic}'.` }] };
    }
    const out = [`📚 ${rows.length} rule(s) matching topic '${topic}':`, ""];
    for (const r of rows) {
      const star = r.is_hardfloor ? "★" : " ";
      const preview = (r.preview || "").replace(/\s+/g, " ").trim().slice(0, 100);
      out.push(`${star} Rule ${r.rule_id} — ${r.title} (~${r.size_tokens_est}t)`);
      out.push(`    ${preview}…`);
    }
    out.push("");
    out.push("★ = hardfloor (always in system prompt). Use clinerules_lookup() for full body.");
    return { content: [{ type: "text", text: out.join("\n") }] };
  }
);

server.tool(
  "clinerules_record_violation",
  "Record an instance of a .clinerules violation. Used by Cline (and post-task analyzers) to track which rules are tripped most often, so the playbook can adapt.",
  {
    rule_id: z.string().describe("Rule ID or slug."),
    task_id: z.string().describe("Cline task ID where the violation occurred."),
    evidence: z.string().describe("Brief evidence text (1-2 sentences, what was violated + how)."),
  },
  async ({ rule_id, task_id, evidence }) => {
    const row = findRule(rule_id);
    const resolvedId = row ? row.rule_id : rule_id;
    db.prepare(`INSERT INTO violations (rule_id, task_id, evidence) VALUES (?,?,?)`)
      .run(resolvedId, task_id, evidence);
    const total = violationCount(resolvedId);
    return {
      content: [{
        type: "text",
        text: `✓ Recorded violation of rule ${resolvedId} for task ${task_id}. Total violations on this rule: ${total}.`,
      }],
    };
  }
);

server.tool(
  "clinerules_reindex",
  "Rebuild the SQLite + FTS5 index from ~/Documents/Cline/Rules/. Call after editing a rule file. Idempotent.",
  {},
  async () => {
    const s = reindex(db, false);
    return {
      content: [{
        type: "text",
        text: `✓ Reindexed: ${s.count} rules, ${s.total_bytes} bytes, ~${s.total_tokens} tokens, ${s.hardfloor_count} hardfloor.`,
      }],
    };
  }
);


// ── FIX 2 of #19173: get_rule91_template ────────────────────────────────────
// Source incident 2026-07-25: ALL 7 rule-91 gate failures in one window came
// from the model RETYPING the 47-repetition U+2550 divider from memory. Small
// and mid-size models cannot reproduce a long unicode box-drawing run reliably;
// they emit ASCII dashes, short runs, or mixed glyphs. Rule 91 says "copy the
// divider, do NOT retype" but there was nothing to copy FROM at generation time.
// This tool hands back the exact glyphs, and optionally assembles the whole
// block so the model never touches a divider at all.
const R91_DIVIDER = String.fromCodePoint(0x2550).repeat(47);

server.tool(
  "get_rule91_template",
  "FIX 2 of #19173. Returns the EXACT rule-91 PICKUP PROMPT skeleton with real 47-char U+2550 divider glyphs, so you copy rather than retype (every observed rule-91 failure came from retyping the divider from memory). Call with no args to get the blank skeleton. Call WITH the field args to get a fully-assembled, gate-passing block you can paste straight into attempt_completion.",
  {
    task_id: z.string().optional().describe("Real numeric Cline task id or idea id (no placeholders). If omitted you get the blank skeleton."),
    topic: z.string().optional().describe("Short topic line, e.g. 'catch-all idea backlog drive'."),
    where_we_left_off: z.array(z.string()).optional().describe("Bullets. Each should carry a #NNNN [disposition] where relevant."),
    open_threads: z.array(z.string()).optional().describe("Numbered-item bodies. EACH must contain a real #NNNN [tag] or the literal '(human-only decision, no idea)' marker."),
    ideas_filed: z.array(z.string()).optional().describe("e.g. ['#19175 [executing]', '#19176 [queued]']"),
    files_touched: z.array(z.string()).optional().describe("Absolute or repo-relative paths, or ['none'] ."),
    verified_ts: z.string().optional().describe("Timestamp string, e.g. '2026-07-25 18:53 PT'."),
  },
  async ({ task_id, topic, where_we_left_off, open_threads, ideas_filed, files_touched, verified_ts }) => {
    if (!task_id) {
      const skeleton = [
        R91_DIVIDER,
        "PICKUP PROMPT (paste into a fresh Cline window)",
        R91_DIVIDER,
        "",
        "Pick up task #<REAL_NUMERIC_ID> - <topic>",
        "",
        "Where we left off (verified <TIMESTAMP> PT):",
        "- <bullet, every #NNNN gets a [disposition]>",
        "",
        "Open threads to drive next:",
        "1. #<id> [disposition] - <action>",
        "   ...or the single line: None - <reason>",
        "",
        "Reference IDs:",
        "- Ideas filed: #<id> [tag]",
        "- Files touched: <paths, or none>",
        "",
        "When done, append to cline_task_ledger.md per rule 07, run order 66.",
        R91_DIVIDER,
      ].join("\n");
      return {
        content: [{
          type: "text",
          text:
            "RULE 91 SKELETON. Copy the dividers verbatim, they are 47 x U+2550.\n" +
            "Tip: call this tool again WITH the field args and it will assemble a gate-passing block for you.\n\n" +
            skeleton +
            "\n\nHARD BANS: no fake ids (IDEA-001), no bare #NNNN without [tag], no placeholders (#NNNN / <...>), " +
            "no em dashes in ops text, the block must live in the `result` parameter (never task_progress).",
        }],
      };
    }

    const cleanId = String(task_id).replace(/[^0-9]/g, "");
    const bullets = (where_we_left_off && where_we_left_off.length)
      ? where_we_left_off.map((b) => (b.trim().startsWith("-") ? b : `- ${b}`))
      : ["- (no state bullets supplied)"];
    const threads = (open_threads && open_threads.length)
      ? open_threads.map((t, i) => `${i + 1}. ${t.replace(/^\d+\.\s*/, "")}`)
      : ["None - nothing left open."];
    const filed = (ideas_filed && ideas_filed.length) ? ideas_filed.join(", ") : "none";
    const files = (files_touched && files_touched.length) ? files_touched.join(", ") : "none";
    const ts = verified_ts || new Date().toISOString().replace("T", " ").slice(0, 16) + " UTC";

    const assembled = [
      R91_DIVIDER,
      "PICKUP PROMPT (paste into a fresh Cline window)",
      R91_DIVIDER,
      "",
      `Pick up task #${cleanId} - ${topic || "continuation"}`,
      "",
      `Where we left off (verified ${ts}):`,
      ...bullets,
      "",
      "Open threads to drive next:",
      ...threads,
      "",
      "Reference IDs:",
      `- Ideas filed: ${filed}`,
      `- Files touched: ${files}`,
      "",
      "When done, append to cline_task_ledger.md per rule 07, run order 66.",
      R91_DIVIDER,
    ].join("\n");

    // Self-check the assembled block against the same em-dash gate the validator uses,
    // so we never hand back a block that our own validator will reject.
    const warn: string[] = [];
    if (/\u2014|\u2015|\u2e3a|\u2e3b/.test(assembled)) {
      warn.push("WARNING: your supplied text contains em dashes. Rule 01 bans them in ops text. Replace with commas or two sentences.");
    }
    const bareIds = [...assembled.matchAll(/#(\d{3,8})\b(\s*\[)?/g)]
      .filter((mm) => !mm[2]).map((mm) => "#" + mm[1])
      .filter((v, i, a) => a.indexOf(v) === i && v !== "#" + cleanId);
    if (bareIds.length) {
      warn.push(`WARNING: bare idea numbers with no [disposition]: ${bareIds.join(", ")}`);
    }

    return {
      content: [{
        type: "text",
        text: (warn.length ? warn.join("\n") + "\n\n" : "") +
          "ASSEMBLED RULE 91 BLOCK (paste verbatim into the attempt_completion `result` parameter):\n\n" +
          assembled,
      }],
    };
  }
);

server.tool(
  "clinerules_validate_completion",
  "PRE-COMPLETION GATE (idea #16224): Validates that a pending attempt_completion result complies with rule 91 (PICKUP PROMPT block required). Call BEFORE attempt_completion. Returns pass/fail with specific violations — if pass=false, fix the listed failures before shipping.",
  {
    result_text: z.string().describe("The result text you plan to pass to attempt_completion."),
    task_id: z.string().optional().describe("Optional Cline task ID for audit telemetry."),
    task_prompt: z.string().optional().describe("FIX 5 of #19173 (coverage gate): the ORIGINAL task prompt text. When supplied, every #NNNN enumerated in the prompt must also appear in result_text, or the gate FAILS with the missing ids named. Escape hatch: a line matching 'EXCLUDED: #NNNN (reason)' counts as covered."),
  },
  async ({ result_text, task_id, task_prompt }) => {
    const failures: string[] = [];
    const DIVIDER_LEN = 47;
    const DIVIDER_GLYPH = String.fromCodePoint(0x2550);
    const lines = result_text.split("\n");

    // ─── Gate 1 (FIXED 2026-07-03): line-based PICKUP PROMPT block detection ─────
    // BUG WAS: searched for inline substring "═══ PICKUP PROMPT ═══" (3 glyphs + text
    // + 3 glyphs on ONE line). The canonical rule-91 template puts 47-char dividers
    // on their OWN lines with "PICKUP PROMPT (paste into a fresh Cline window)" on a
    // separate line. A perfectly-formatted prompt NEVER contained that inline
    // substring → ALWAYS false-negative (MISSING_PICKUP_PROMPT), while a broken
    // inline short-divider prompt DID contain it → false positive. This made the
    // validator actively harmful (failed correct prompts, rewarded broken ones),
    // so agents learned to ignore it and real violations slipped through.
    //
    // FIX: detect the block structurally — a full 47-char divider, immediately
    // followed by a "PICKUP PROMPT ..." header line, with a closing divider.
    const isFullDivider = (s: string): boolean => {
      const t = s.trimEnd();
      return t.length === DIVIDER_LEN && new RegExp("^" + DIVIDER_GLYPH + "+$").test(t);
    };
    // Find all full-length divider line indices (Gate 2 scan, merged with Gate 1)
    const dividerIndices: number[] = [];
    for (let i = 0; i < lines.length; i++) {
      if (isFullDivider(lines[i])) {
        dividerIndices.push(i);
        const stripped = lines[i].trimEnd();
        for (const ch of stripped) {
          if ((ch as any).codePointAt(0) !== 0x2550) {
            failures.push(`DIVIDER_WRONG_GLYPH: line ${i+1} uses wrong character (U+${(ch as any).codePointAt(0)?.toString(16)}) instead of U+2550.`);
            break;
          }
        }
      } else {
        const stripped = lines[i].trimEnd();
        if (stripped.length > 20 && new RegExp("^" + DIVIDER_GLYPH + "+$").test(stripped)) {
          failures.push(`DIVIDER_WRONG_LENGTH: line ${i+1} divider is ${stripped.length} chars, must be exactly 47 chars of U+2550. Copy the divider from rule 91 template.`);
        }
      }
    }
    // Detect PICKUP PROMPT header on the line immediately after an opening divider
    const pickupHeaderIdx = (() => {
      for (const di of dividerIndices) {
        const hdrIdx = di + 1;
        if (hdrIdx < lines.length) {
          const hdr = lines[hdrIdx].trim();
          if (/^PICKUP PROMPT\b/i.test(hdr)) return hdrIdx;
        }
      }
      return -1;
    })();
    const hasBlock = pickupHeaderIdx !== -1 && dividerIndices.length >= 2;
    if (!hasBlock) {
      failures.push("MISSING_PICKUP_PROMPT: result text does not contain a structurally-valid PICKUP PROMPT block (47-char U+2550 divider, then 'PICKUP PROMPT ...' header, then another 47-char divider). Add the rule-91 pickup prompt before calling attempt_completion.");
    }
    // Gate 2/3: divider pairing + block extraction
    let pickupBlock = "";
    if (dividerIndices.length === 0) {
      failures.push("DIVIDER_MISSING: no valid 47-char U+2550 divider lines found. Pickup prompt requires 47-char U+2550 dividers — copy them from rule 91 template.");
    } else if (dividerIndices.length < 2) {
      failures.push(`DIVIDER_UNPAIRED: only ${dividerIndices.length} full-length divider(s) found — need at least 2 (opening + closing).`);
    } else {
      const firstDiv = dividerIndices[0];
      const lastDiv = dividerIndices[dividerIndices.length - 1];
      pickupBlock = lines.slice(firstDiv, lastDiv + 1).join("\n");
    }
    // Gate 4: literal placeholder tokens (including Unicode dash variants — Violation #17)
    // Catches #NNNN, #0000, #XXXX, <task_id>, AND #— / #– / #― etc. (em-dash placeholders)
    const _dashPlaceholder = /#(?:NNNN|0000|XXXX|<task_id>|<timestamp\s*PT>|(?:[\u2010-\u2015\u2212\u2E3A\u2E3B\-—–]))/i;
    if (_dashPlaceholder.test(pickupBlock)) {
      failures.push("PLACEHOLDER_DETECTED: literal placeholder token found in pickup prompt (#NNNN, #0000, #XXXX, #— em-dash, <task_id>, etc.). Replace with real values — call create_idea for real integer IDs.");
    }
    // Gate 4c (NEW 2026-07-24, Violation #17): open-thread items without real idea numbers
    // Each numbered item under "Open threads" MUST have #<integer> [tag] OR (human-only decision — no idea) marker.
    // Catches the pattern where agents list actionable items as "open threads" with fake/placeholder tags
    // but never call create_idea (Violation #14 + #17 pattern).
    if (pickupBlock) {
      const otMatch = pickupBlock.match(/open\s+threads?\s+to\s+drive\s+next\s*:?\s*\n([\s\S]*?)(?:\n\s*reference\s+ids|\n\s*when\s+done|$)/i);
      if (otMatch) {
        const otSection = otMatch[1];
        // Match numbered list items: "1. ...", "2. ...", etc.
        const items = otSection.split(/\n(?=\d+\.\s)/).filter((s: string) => /^\s*\d+\.\s/.test(s));
        for (const item of items) {
          const hasRealIdea = /#\d{1,8}\s*\[/.test(item);  // #NNNN followed by [
          const hasHumanOnlyMarker = /human-only\s+decision|no\s+idea\)/i.test(item);
          if (!hasRealIdea && !hasHumanOnlyMarker) {
            const firstLine = item.split("\n")[0].trim().slice(0, 80);
            failures.push(`UNFILED_OPEN_THREAD: open-thread item lacks real idea number or human-only marker: "${firstLine}...". Either call create_idea for a real #NNNN [tag], or mark "(human-only decision — no idea)". Listing agent-doable work as an open thread without filing it is a rule-29 + rule-91 violation.`);
          }
        }
      }
    }
    // Gate 4b (NEW 2026-07-03): missing task ID. Rule 91 requires "Pick up task #<real task id> — <topic>".
    // Prior validator only caught LITERAL placeholders (#NNNN), so a prompt that simply OMITTED the
    // task id ("Pick up task — final-notice cleanup") passed while violating rule 91. This catches the omission.
    if (pickupBlock) {
      const taskLineMatch = pickupBlock.match(/^Pick up task\b[^\n]*$/im);
      if (taskLineMatch) {
        const taskLine = taskLineMatch[0];
        if (!/#\d+/.test(taskLine)) {
          failures.push("MISSING_TASK_ID: the 'Pick up task' line has no #<numeric id>. Rule 91 requires 'Pick up task #<real task id> — <topic>'. Add the real Cline task id.");
        }
      } else {
        failures.push("MISSING_TASK_LINE: no 'Pick up task ...' line found in pickup prompt. Rule 91 requires a 'Pick up task #<id> — <topic>' line.");
      }
    }

    if (/see\s+handoff\s+file/i.test(pickupBlock)) {
      failures.push("PICKUP_BY_REFERENCE: 'see handoff file' detected in pickup prompt — the block must be INLINE, not a pointer to an external file.");
    }

    if (/hold\s+until\s+Ruben\s+confirms|wait\s+before\s+acting|pause\s+until|ask\s+first\s+if/i.test(pickupBlock)) {
      failures.push("R91_WAIT_STATE: forbidden wait-state language in pickup prompt.");
    }

    // ── RULE 29 (act-dont-defer) ──
    if (/(?:I.ll|I will)\s+(?:mention this|raise this|flag this)\s+and\s+Ruben\s+(?:decides|can decide|will decide)/i.test(result_text)) {
      failures.push("R29_DECISION_QUEUE: 'I'll mention this and Ruben decides' — act first, report status. No decision queues.");
    }
    if (/(?:the\s+)?(?:fleet|executor|orchestrator|cron)\s+(?:agent\s+)?(?:will|should|can)\s+(?:handle|do|pick\s+up|take\s+care\s+of)\s+(?:it|this|that)/i.test(pickupBlock)) {
      failures.push("R29_DEFER_TO_SYSTEM: deferring to fleet/executor/cron without verifying capability. Verify or act directly.");
    }
    if (/(?:wait\s+for|let)\s+(?:the\s+)?(?:other|parallel|sibling)\s+(?:Cline|agent)\s+(?:window|session)s?/i.test(pickupBlock)) {
      failures.push("R29_PARALLEL_WAIT: waiting for parallel windows forbidden. Each window works independently.");
    }

    // ── RULE 120 (context-is-not-an-excuse) ──
    if (/(?:due\s+to|given|because\s+of|owing\s+to)\s+(?:the\s+)?(?:context|token)\s+(?:constraints?|limitations?|window|size|budget)/i.test(result_text)) {
      failures.push("R120_CONTEXT_EXCUSE: naming context/token limits as reason for doing less. <300K=work fully, >=500K=compress.");
    }
    if (/(?:to\s+conserve|to\s+save|preserving|conserving)\s+(?:context|tokens)/i.test(result_text)) {
      failures.push("R120_CONTEXT_EXCUSE: 'conserving context' is never a valid reason to shortcut.");
    }

    // ── RULE 01 (voice-and-persona) ──
    const looksLikeOps = /\b(?:student|ticket|Jon|Vicky|Moodle|QB|Authnet|externship|NREMT|class|section|instructor|enrollment)\b/i.test(result_text);
    if (looksLikeOps) {
      if (/\u2014|\u2015|\u2e3a|\u2e3b/.test(result_text)) {
        failures.push("R01_EM_DASH: em dashes in ops text. Use commas, parentheses, or two sentences.");
      }
      if (/\b(?:the\s+)?(?:finance|tech|support|dev)\s+(?:department|team)\b/i.test(result_text)) {
        failures.push("R01_FAKE_DEPARTMENT: invoking nonexistent department. Name the person.");
      }
    }

    // ── RULE 02 (no-apologies-in-student-emails) ──
    const looksLikeStudent = /\b(?:Hi|Hello|Dear)\b.*\b(?:student|EMS)/i.test(result_text) || /\b(?:your\s+course|your\s+grade|your\s+exam|your\s+enrollment|your\s+deadline)\b/i.test(result_text);
    if (looksLikeStudent) {
      if (/(?:I(?:.m|\s+am)|we\s+are|we.re)\s+(?:sorry|very\s+sorry)/i.test(result_text)) {
        failures.push("R02_APOLOGY: 'sorry' in student-facing text. Neutral acknowledgement + fix action only.");
      }
      if (/(?:I|we)\s+apologi[sz]e/i.test(result_text)) {
        failures.push("R02_APOLOGY: 'apologize' in student-facing text. Legal exposure — never apologize in writing.");
      }
    }

    // ── RULE 317 (completion-confidence / acquisition gate) ─────────────────
    // Ruben 2026-08-12: the #1 recurring wrong-claim is LLM/fleet/routing state
    // recited from memory. Rule 317's Acquisition Gate requires every material
    // state claim to be re-probed live and carry the evidence marker. This
    // detects unverified fleet/LLM/host state claims in the result.
    {
      const stateWords = /\b(down|offline|dead|unhealthy|degraded|saturated|idle|up|online|alive|healthy|green|recovered|restored|serving|crashed|unresponsive|wedged|stall(?:ed|ing)?)\b/i;
      const fleetCtx = /\b(fleet|frankenstein|litellm|router|host|pod|box|model|120b|405b|free[- ]local|wopr|cesar|cato|backend|serving)\b/i;
      const evidenceMarker = /\b(verified|probed|probe|live\s+(?:call|request|probe)|response\s+header|registry|curl|returned|audit\s+log|measured|confirmed|checked|reconciled|hypervisor|gpu-?util|httpx?)\b/i;
      const unverifiedClaims: string[] = [];
      for (let i = 0; i < lines.length; i++) {
        const line = lines[i];
        if (!fleetCtx.test(line) || !stateWords.test(line)) continue;
        // evidence may live on the line or its immediate neighbours
        const ctx = (lines[i - 1] || "") + "\n" + line + "\n" + (lines[i + 1] || "");
        if (!evidenceMarker.test(ctx)) {
          const clipped = line.trim().slice(0, 96);
          if (!unverifiedClaims.includes(clipped)) unverifiedClaims.push(clipped);
        }
      }
      if (unverifiedClaims.length > 0) {
        failures.push(
          `R317_UNVERIFIED_STATE: ${unverifiedClaims.length} line(s) assert LLM/fleet/host state with no live-probe evidence: ` +
          unverifiedClaims.map((s: string) => `"${s}"`).join("; ") + `. ` +
          `Rule 317 Acquisition Gate: re-probe each material state claim (frankenstein_registry / verify_routing / response headers) ` +
          `and add a '(verified: ...)' marker quoting what the probe returned. Never recite fleet/LLM status from memory.`
        );
      }
    }

    // ── RULE 317 / idea #25888: REVERSAL LOG (completion-time, zero per-turn overhead) ──
    // Ruben 2026-08-12 "Approved 25888" + steering "how do we deal with this potential
    // defect" (per-turn capture cost). Design: NO ledger written turn-by-turn. The
    // check is one structural scan of the completion text itself: rule 317 Obligation 2
    // requires the completion to contain a Reversal Log section (or state "No reversals").
    // The agent fills it ONCE at completion time — the last thing it writes before
    // shipping. A flip detected while re-probing (Obligation 1) MUST be listed here with
    // its RCA bucket and causal-rule update. This catches the self-reported reversal the
    // model would otherwise silently drop, at the only moment we cannot be skipped:
    // the completion gate.
    {
      const reversalHeader = /reversal\s*log|conclusion\s*flips?\s*:\s*$/im;
      if (!reversalHeader.test(result_text)) {
        failures.push(
          `R317_REVERSAL_LOG: completion has no Reversal Log section. Rule 317 Obligation 2 (idea #25888): ` +
          `write a "# Reversal Log" section that either states "No reversals this window" or lists EVERY within-window flip as ` +
          `"- initial conclusion → corrected conclusion | RCA bucket (wrong premise|stale assumption|unread source|insufficient probe|scope error) | causal rule updated (file/slug) or filed idea #NNNN". ` +
          `If a probe during the acquisition gate contradicted an earlier statement, that flip MUST appear here with its causal-rule fix.`
        );
      } else {
        // Section present: every listed flip must carry an RCA bucket; any flip citing a
        // rule update must reference a real file/slug, or a filed idea number with a disposition.
        // SECTION SPLIT FIX (2026-08-14, positive-control C). This split on U+2502
        // BOX DRAWINGS LIGHT VERTICAL. The rule-91 divider is U+2550, so the split
        // never matched and the reversal section was the ENTIRE result including the
        // pickup prompt. Split on the real divider, literal header as fallback.
        // REVERSAL SCAN WINDOW (2026-08-14). Previously this bounded only the END
        // ("everything before the PICKUP PROMPT") and never the START, so EVERY bullet
        // in the whole result was eligible to be read as a flip line. A completion that
        // listed guard-test results as bullets with arrows got flagged for a missing RCA
        // bucket even though its actual Reversal Log was correctly bucketed. That false
        // positive punishes detailed completions, the opposite of what rule 317 wants.
        // Bound BOTH ends: start at the Reversal Log header, stop at the pickup prompt.
        // No true positive is lost, because rule 317 requires flips to be listed under
        // that header in the first place.
        const _revStart = result_text.search(/^#{0,3}\s*reversal\s*log/im);
        const _revBody = _revStart >= 0 ? result_text.slice(_revStart) : result_text;
        const reversalSection = _revBody
          .split(/\u2550{5,}[\s\S]{0,60}?PICKUP PROMPT/i)[0]
          .split(/PICKUP PROMPT \(paste into a fresh Cline window\)/i)[0];
        // FLIP-PHRASING FIX (2026-08-14, positive-control C). The unbucketed-flip
        // filter matched ONLY the arrow glyphs. Rule 317's own body writes flips with
        // the word 'became', and agents copy that phrasing, so unbucketed flips in that
        // form passed the gate untouched. A gate that misses the phrasing its own rule
        // text uses is decorative. Detect arrow AND verbal forms.
        const FLIP_FORM = /\u2192|=>|->|\bbecame\b|\bbecomes\b|\bturned out to be\b|\bwas actually\b|\bcorrected to\b/i;
        const RCA_BUCKET = /wrong premise|stale assumption|unread source|insufficient probe|scope error/i;
        const flipLines = reversalSection.split("\n").filter((l: string) => FLIP_FORM.test(l) && RCA_BUCKET.test(l));
        const flipsWithoutRca = reversalSection.split("\n").filter((l: string) => {
          const t = l.trim();
          if (!/^[-*]\s/.test(t)) return false;
          if (!FLIP_FORM.test(t)) return false;
          if (/no reversals/i.test(t)) return false;
          return !RCA_BUCKET.test(t);
        });
        if (flipsWithoutRca.length > 0) {
          failures.push(
            `R317_REVERSAL_LOG: reversal log line(s) lack an RCA bucket: ` +
            flipsWithoutRca.map((s: string) => `"${s.trim().slice(0, 80)}"`).join("; ") +
            `. Each flip needs one of: wrong premise | stale assumption | unread source | insufficient probe | scope error.`
          );
        }
      }
    }

    // ── RULE 321 (idea #26349): GASLIGHT GATE ──────────────────────────────
    // Ruben 2026-08-14 "approved -> 26349": the gaslighting pattern is an agent
    // proposing a deliverable, Ruben approving, and then a hidden gate (false
    // checkpoint, undisclosed requirement) blocking deployment — or a completion
    // claiming done while still deferring buildable work elsewhere. Same family
    // as R317: one structural scan of the completion text, zero per-turn cost.
    // FAR ONLY ON TEXTUAL CONTRADICTION to keep false positives off valid
    // completions: (a) a work-done claim AND deferral-to-future-window in the
    // same body, or (b) explicit "after approval" + additional-gate noun. The
    // pickup block is STRIPPED first so its structural "Open threads to drive
    // next" wording (compliant by rule 91) cannot trip the deferral scan.
    {
      const _gaslightBody = result_text.replace(/\u2550{5,}[\s\S]*?PICKUP PROMPT[\s\S]*$/i, "");
      const workDoneClaim = /\b(?:task|build|work|deliverable|deploy(?:ment)?)\s+(?:is\s+)?(?:done|complete|completed|deployed|shipped|finished)\b/i;
      const deferToFuture = /\b(?:file|filed|files|filing)\s+(?:it|this|that)?\s*(?:as)?\s*an?\s+idea\s+for\s+(?:a\s+)?(?:future|next|later)\s+(?:window|session)\b|\bnext\s+window\s+(?:should|will|can)\b|\bdefer(?:red|ring)?\s+(?:it|this|the\s+work|to\s+a\s+future)\b|\b(?:will|to\s+be)\s+handled\s+in\s+a\s+(?:future|later|next)\s+(?:window|session|round)\b/i;
      const postApprovalGate = /(?:after\s+(?:my|your|the|Ruben's)?\s*approval|once\s+(?:you|I|it'?s|it\s+is)\s+approved|post-approval)[^\n]{0,80}\b(?:additional|another|one\s+more|separate|new|further)\s+(?:gate|checkpoint|requirement|hurdle|approval|review)\b/i;
      const _gaslightIssues: string[] = [];
      if (workDoneClaim.test(_gaslightBody) && deferToFuture.test(_gaslightBody)) {
        _gaslightIssues.push("completion claims the task/build/work is done, deployed or shipped while ALSO deferring buildable work to a future window, session, or idea-for-later");
      }
      if (postApprovalGate.test(_gaslightBody)) {
        _gaslightIssues.push("result introduces an additional gate, checkpoint, or requirement AFTER approval was given — every gate must be stated in the proposal BEFORE approval");
      }
      if (_gaslightIssues.length > 0) {
        failures.push(
          `R321_GASLIGHT_GATE: ${_gaslightIssues.join("; ")}. ` +
          `Rule 321 (idea #26349): "Approved" means DEPLOY. A post-approval gate undermines the approval; ` +
          `if a REAL blocker surfaces instead, state it in the next tool-bearing turn with a concrete unblock path ` +
          `and a filed idea # — never as a hidden pre-existing requirement, never as silently-pending work next to a done claim. ` +
          `Buildable work deferred without a filed idea is a rule-29 + rule-300 violation.`
        );
      }
    }

    // ── FIX 5 of #19173: COVERAGE GATE ──────────────────────────────────────
    // Source incident 2026-07-25: a catch-all window prompt enumerated 39 explicit
    // idea ids. The first attempt_completion accounted for 7 of them and shipped.
    // The existing bare-number scan asks "does every #NNNN in the RESULT have a tag"
    // which passes TRIVIALLY if the agent simply omits most of the numbers. This is
    // the read-side twin: does every #NNNN in the PROMPT appear in the result.
    if (task_prompt && task_prompt.trim().length > 0) {
      const idRe = /#(\d{3,8})\b/g;
      const promptIds = new Set<string>();
      let m: RegExpExecArray | null;
      while ((m = idRe.exec(task_prompt)) !== null) promptIds.add(m[1]);
      const resultIds = new Set<string>();
      idRe.lastIndex = 0;
      while ((m = idRe.exec(result_text)) !== null) resultIds.add(m[1]);
      // Explicit scope-cut escape hatch
      const excludedIds = new Set<string>();
      const exRe = /EXCLUDED:\s*#(\d{3,8})/gi;
      while ((m = exRe.exec(result_text)) !== null) excludedIds.add(m[1]);
      const missing = [...promptIds].filter((id) => !resultIds.has(id) && !excludedIds.has(id));
      if (missing.length > 0) {
        failures.push(
          `COVERAGE_GAP: the task prompt enumerated ${promptIds.size} idea id(s); the result covers ${promptIds.size - missing.length}. ` +
          `Missing ${missing.length}: ${missing.map((i) => "#" + i).join(", ")}. ` +
          `Tag every prompt-enumerated id with a rule-109 disposition, or write "EXCLUDED: #NNNN (reason)" for deliberate scope cuts.`
        );
      }
    }

    // ── FIX 1 of #19173: BARE-NUMBER TAG SCAN (all failures at once) ────────
    // Rule 91 hardfloor: every #NNNN in the ENTIRE result needs a [disposition].
    // Reported as ONE aggregated failure listing every offender, not one-at-a-time,
    // so the agent fixes them in a single round trip instead of N ping-pongs.
    {
      // 2026-08-01 Ruben directive: queued is BANNED as a parking-lot excuse.
      // queued in the tag text is a HARD FAIL, not just "bare number." See rule 161.
      const VALID_TAGS = /^(deployed|executing|blocked|proposed|rejected|superseded|awaiting_review|approved|closed|done)$/i;
      const queuedTags: string[] = [];
      const bare: string[] = [];
      const scanRe = /#(\d{3,8})\b(\s*\[([^\]]*)\])?/g;
      let sm: RegExpExecArray | null;
      while ((sm = scanRe.exec(result_text)) !== null) {
        const id = sm[1];
        const tag = sm[3];
        if (!tag || !VALID_TAGS.test(tag.trim())) {
          if (tag && /queued/i.test(tag.trim())) {
            if (!queuedTags.includes(id)) queuedTags.push(id);
          } else {
            if (!bare.includes(id)) bare.push(id);
          }
        }
      }
      if (queuedTags.length > 0) {
        failures.push(
          `QUEUED_TAG_BANNED: ${queuedTags.length} idea number(s) have [queued] disposition which is BANNED by Ruben directive (2026-08-01, rule 161): ` +
          `${queuedTags.map((i) => "#" + i).join(", ")}. ` +
          `Approved ideas are [executing], not queued. If the work is not moving, use [blocked] and name the obstruction.`
        );
      }
      if (bare.length > 0) {
        failures.push(
          `BARE_IDEA_NUMBERS: ${bare.length} idea number(s) in the result have no valid [disposition] bracket: ` +
          `${bare.map((i) => "#" + i).join(", ")}. ` +
          `Every #NNNN needs one of [deployed|executing|blocked|proposed|rejected|superseded|awaiting_review].`
        );
      }

      // SELF_CONTRADICTING_DISPOSITION (idea #25185, 2026-08-08).
      // Ruben: "I'm being told by Cline agents that things are completed which are
      // not being completed." Root cause: when an agent HAND-SHIPS a fix (rule 267
      // GATE C) it edits the server but never stamps orchestrator_ideas, so the row
      // stays proposed/idle. reconcile_ideas then faithfully returns [proposed],
      // the agent pastes that tag beside prose that honestly says FIXED, and the
      // completion contradicts itself. Every prior gate passed it: rule 91 only
      // checks a tag EXISTS, rule 267 only checks a reconcile CALL happened.
      // Neither compares the tag to the CLAIM. This does.
      const contradictions: string[] = [];
      const claimWord = /\b(FIXED|DEPLOYED|SHIPPED|LIVE IN PRODUCTION|DONE|COMPLETED|VERIFIED LIVE|HAND-SHIPPED)\b/i;
      const notYetTag = /#(\d{3,8})\s*\[(proposed|executing|awaiting_review)\]/gi;
      // 2026-08-12 false-positive fix #3 (idea #25935): pre-strip disposition
      // brackets, rule-91 boilerplate, and neighbouring "#NNNN [tag]" tokens from
      // the FULL text FIRST, then slice the window from the STRIPPED text using a
      // position map. The prior order (slice-then-strip) truncated neighbouring
      // "[deployed]" brackets mid-token at the 220-char window boundary (e.g. the
      // slice ends at "...#25926 [deplo"), so the strip regex could not match the
      // partial bracket and the surviving bare "deplo(yed)" fragment or a cut
      // "Ideas filed this session: #25925 [deployed" line tripped claimWord for an
      // innocent [executing] item 200 chars away. Stripping the whole text first
      // makes truncation harmless: whatever survives in the window is already
      // bracket-free prose.
      // Position-preserving strip: replace each stripped region with SPACES of
      // equal length so cm.index from result_text remains valid in strippedFull.
      // (2026-08-08 fixes #1+#2 folded in: disposition brackets contain the
      // literal word DEPLOYED, and rule 91's own boilerplate contains DONE.)
      const padSpaces = (m: string) => " ".repeat(m.length);
      const strippedFull = result_text
        .replace(/\[(deployed|executing|blocked|proposed|rejected|superseded|awaiting_review)\]/gi, padSpaces)
        .replace(/When done,[^\n]*/gi, padSpaces)
        .replace(/At wrap-up,[^\n]*/gi, padSpaces)
        .replace(/run order 66/gi, padSpaces);
      let cm: RegExpExecArray | null;
      while ((cm = notYetTag.exec(result_text)) !== null) {
        const id = cm[1];
        const tag = cm[2].toLowerCase();
        // Window is sliced from the ALREADY-STRIPPED text, so a slice boundary
        // can never cut a bracket mid-token and resurrect its inner word.
        const from = Math.max(0, cm.index - 220);
        const to = Math.min(strippedFull.length, cm.index + cm[0].length + 220);
        const window = strippedFull.slice(from, to);
        if (claimWord.test(window)) {
          const key = `#${id} [${tag}]`;
          if (!contradictions.includes(key)) contradictions.push(key);
        }
      }

      if (contradictions.length > 0) {
        failures.push(
          `SELF_CONTRADICTING_DISPOSITION: ${contradictions.length} idea(s) are described with completion language ` +
          `(FIXED/DEPLOYED/SHIPPED/DONE/VERIFIED LIVE) while carrying a NOT-YET-DONE tag: ${contradictions.join(", ")}. ` +
          `Either (a) the work IS shipped -- then stamp the record first: UPDATE orchestrator_ideas SET status='deployed', ` +
          `dev_stage='ready_for_review', implemented_at=NOW(), implemented_files=JSON_ARRAY('/path') WHERE id=N; ` +
          `re-run reconcile_ideas, and use the [deployed] tag it returns. Or (b) the work is NOT shipped -- then remove the ` +
          `completion language. A completion that says FIXED next to [proposed] is unreadable to Ruben (idea #25185).`
        );
      }

      // ── RULE 317 MECHANICAL CORPUS FEED (idea #26435, 2026-08-14) ────────
      // Ruben 2026-08-14: 317 Obligation 2 previously updated ONLY the causal
      // clinerules file. The reversals kept recurring because the correction
      // never reached the EMSU self-improvement loop (ai_learned_corrections ->
      // CorpusRealtimeIngester -> emsu_preference_corpus -> RAG context + LoRA).
      // This makes the corpus write MECHANICAL: when the validator itself detects
      // a self-contradicting completion, it POSTs the correction to
      // api/cline_correction_ingest.php so a future window retrieves it from RAG
      // context BEFORE it repeats the lie. Fire-and-forget, 4s bounded, non-fatal:
      // a corpus-write hiccup must never change the validation verdict, and the
      // correction still lands zero-times or one-time via dedup upsert.
      if (contradictions.length > 0) {
        try {
          const ctrl = new AbortController();
          const timer = setTimeout(() => ctrl.abort(), 4000);
          await fetch("https://www.emsuniversity.com/emtskills/api/cline_correction_ingest.php", {
            method: "POST",
            signal: ctrl.signal,
            headers: {
              "Content-Type": "application/json",
              "X-Ledger-Key": "emsu-cline-ledger-2026-04-22-rj9k3m7q",
            },
            body: JSON.stringify({
              issue_category: "self_contradicting_disposition",
              trigger_pattern: "completion prose says FIXED/DEPLOYED/DONE next to a [proposed]/[executing] idea tag",
              ai_approach: "hand-shipped or narrated a fix without stamping orchestrator_ideas before completing",
              correct_approach:
                "UPDATE orchestrator_ideas SET status='deployed' then re-run reconcile_ideas and use the [deployed] tag it returns, OR remove the completion language",
              negative_example: contradictions.join(", ").slice(0, 500),
              correction_type: "procedural",
              source_task_id: task_id || "",
            }),
          }).catch(() => undefined);
          clearTimeout(timer);
        } catch {
          /* non-fatal: corpus write is best-effort; validation verdict unchanged */
        }
      }
    }


    // ── EXISTENCE + IDENTITY GATE (2026-07-28, source incident below) ───────
    // A Cline window shipped a pickup prompt citing #19898-#19904 as ideas it
    // had "filed". It had filed NOTHING. It invented seven plausible sequential
    // integers and tagged each [proposed]. This validator returned ALL PASSED,
    // because every gate above is a SYNTAX check: "is each #NNNN followed by a
    // valid [disposition] bracket". A fabricated number with a correct-looking
    // tag is indistinguishable from a real one to a regex.
    //
    // Worse, when the fabricated ids were finally checked against the DB, ALL
    // SEVEN EXISTED, pointing at unrelated work (an Argus browser extension, an
    // email-routing backlog, an Artemis context-length mismatch). So a bare
    // exists/not-exists check would ALSO have passed. In a live orchestrator the
    // id space is dense, and any plausible integer an agent invents probably
    // resolves to SOMETHING.
    //
    // Therefore this gate does two things:
    //   1. HARD FAIL on any cited id that does not exist.
    //   2. ECHO THE REAL TITLE of every cited id back to the agent, so a
    //      fabricated-but-existing id is visually impossible to miss. The agent
    //      cannot claim "#19899 [proposed] Add Klarna to SLS oracle" when the
    //      validator prints back "#19899 = Argus extension: Add keyboard shortcut".
    //
    // Read-only, 8s bounded, fails OPEN on network error so a WOPR outage never
    // blocks a legitimate completion.
    let identityEcho = "";
    {
      const citedIds: string[] = [];
      const cRe = /#(\d{4,8})\b/g;
      let cm: RegExpExecArray | null;
      while ((cm = cRe.exec(result_text)) !== null) {
        if (!citedIds.includes(cm[1])) citedIds.push(cm[1]);
      }
      if (citedIds.length > 0) {
        // 2026-08-05: FAIL-CLOSED + RETRY.
        // Previously a single 8s fetch with a silent catch -> on any hiccup the
        // gate degraded to a soft "SKIPPED" note and the completion PASSED with
        // idea numbers totally unverified. That is a fail-OPEN anti-lie gate:
        // it protects you exactly when it happens to be up, which is the one
        // property a lie-detector must not have. Now: 3 attempts with backoff,
        // and if all 3 fail the validation HARD-FAILS so the agent cannot ship
        // unverified idea numbers by getting unlucky with the network.
        let data: any = null;
        let lastErr = "";
        for (let attempt = 1; attempt <= 3; attempt++) {
          try {
            const ctrl = new AbortController();
            const timer = setTimeout(() => ctrl.abort(), 15000);
            const resp = await fetch(
              "https://www.emsuniversity.com/emtskills/api/orchestrator/idea_exists.php?ids=" +
                encodeURIComponent(citedIds.join(",")),
              { signal: ctrl.signal }
            );
            clearTimeout(timer);
            data = await resp.json();
            if (data && data.ok) break;
            lastErr = "endpoint returned ok=false";
            data = null;
          } catch (e: any) {
            lastErr = String(e && e.message ? e.message : e).slice(0, 120);
            data = null;
          }
          if (attempt < 3) await new Promise((r) => setTimeout(r, 1000 * attempt));
        }
        try {

          if (data && data.ok && data.ideas) {
            const missing: string[] = Array.isArray(data.missing)
              ? data.missing.map((x: any) => String(x))
              : [];
            if (missing.length > 0) {
              failures.push(
                `FABRICATED_IDEA_ID: ${missing.length} cited idea number(s) DO NOT EXIST in orchestrator_ideas: ` +
                `${missing.map((i) => "#" + i).join(", ")}. ` +
                `You cited an idea you never filed. Call create_idea to get real integer IDs, then re-validate.`
              );
            }
            const lines: string[] = [];
            for (const id of citedIds) {
              const rec = data.ideas[id];
              if (rec && rec.exists) {
                lines.push(`  #${id} [${rec.status}] ${String(rec.title).slice(0, 88)}`);
              } else {
                lines.push(`  #${id} *** DOES NOT EXIST ***`);
              }
            }
            identityEcho =
              "\n\nIDENTITY ECHO (confirm each title matches what your result claims):\n" +
              lines.join("\n") +
              "\nIf ANY title above is unrelated to what you wrote next to that number, " +
              "you cited the wrong idea. Fix it before shipping.";
          }
        } catch (e: any) {
          lastErr = String(e && e.message ? e.message : e).slice(0, 120);
          data = null;
        }
        if (!data) {
          // FAIL CLOSED. An unverifiable claim is not a passing claim.
          failures.push(
            `IDENTITY_GATE_UNAVAILABLE: could not verify ${citedIds.length} cited idea id(s) after 3 attempts ` +
            `(last error: ${lastErr || "unknown"}). The existence gate FAILS CLOSED by design: an agent must not be ` +
            `able to ship unverified idea numbers just because the network hiccuped. Retry in a moment. If the ` +
            `endpoint is genuinely down, remove every #NNNN citation from the result or fix the endpoint first.`
          );
          identityEcho =
            "\n\nIDENTITY ECHO: FAILED (idea_exists.php unreachable after 3 attempts). " +
            "This is now a HARD FAILURE, not a soft skip.";
        }

      }
    }

    const pass = failures.length === 0;

    // Log validation
    try {
      db.prepare("INSERT INTO violations (rule_id, task_id, evidence) VALUES (?,?,?)")
        .run("91", task_id || "unknown", pass ? "VALIDATION_PASS: all multi-rule gates passed (R91+R29+R120+R01+R02+R317+R321+IDENTITY)" : "VALIDATION_FAIL: " + failures.join("; "));
    } catch { /* telemetry */ }
    // ── STRUCTURAL GATE (idea #20251) ──
    // Before this patch the validator was purely ADVISORY: it returned a failure
    // report and did nothing else, so agents read the failures and called
    // attempt_completion anyway (observed 2026-07-30: BARE_IDEA_NUMBERS reported,
    // completion shipped regardless). Now a FAILURE writes a gate file that
    // clinerules_check_gate reads, giving the gate a real side effect.
    const gateFile = path.join(os.tmpdir(), task_id
      ? `clinerules_completion_gate_BLOCKED_${task_id}`
      : `clinerules_completion_gate_BLOCKED`);
    try {
      if (pass) {
        if (fs.existsSync(gateFile)) fs.unlinkSync(gateFile);
      } else {
        fs.writeFileSync(gateFile, JSON.stringify({
          blocked: true,
          task_id: task_id || "unknown",
          failures,
          timestamp: new Date().toISOString(),
          message: "attempt_completion is BLOCKED. Fix the failures, re-run clinerules_validate_completion, then clinerules_check_gate."
        }, null, 2));
      }
    } catch (e: any) {
      if (!pass) failures.push(`GATE_FILE_WRITE_FAILED: ${e.message}`);
    }

    if (pass) {
      return {
        content: [{
          type: "text",
          text: "\u2705 RULE 91 GATES: ALL PASSED\n\nDivider: 47 U+2550 chars \u2713\nPickup prompt present \u2713\nNo placeholders \u2713\nNo pickup-by-reference \u2713\nNo wait-state phrases \u2713\nCited idea IDs exist \u2713" + identityEcho + "\n\nSafe to call attempt_completion.",
        }],
      };
    }
    return {
      content: [{
        type: "text",
        text: `\u274c RULE 91 GATES: ${failures.length} FAILURE(S)\n\n${failures.map((f: string, i: number) => `${i+1}. ${f}`).join("\n")}${identityEcho}\n\nFix these before calling attempt_completion. The completion is blocked until all gates pass.`,
      }],
    };
  }
);

// ─── clinerules_check_gate (idea #20251) ───────────────────────────────────
// The read half of the structural gate. clinerules_validate_completion writes
// the gate file on FAILURE; this tool reports it. Rule 91 requires calling this
// immediately before attempt_completion.
server.tool(
  "clinerules_check_gate",
  "PRE-COMPLETION GATE CHECK (idea #20251): reports whether a validation gate file is blocking attempt_completion. Call this AFTER clinerules_validate_completion and BEFORE attempt_completion. BLOCKED means you must fix the listed failures and re-validate. CLEAR means it is safe to ship.",
  {
    task_id: z.string().describe("The Cline task ID whose gate file should be checked."),
  },
  async ({ task_id }) => {
    const gateFile = path.join(os.tmpdir(), task_id
      ? `clinerules_completion_gate_BLOCKED_${task_id}`
      : `clinerules_completion_gate_BLOCKED`);
    try {
      if (fs.existsSync(gateFile)) {
        const data = JSON.parse(fs.readFileSync(gateFile, "utf-8"));
        return {
          content: [{
            type: "text" as const,
            text:
              "\u274c RULE 91 GATE BLOCKED\n\nGate file: " + gateFile +
              "\nTask ID: " + data.task_id +
              "\nFailures: " + (data.failures || []).join("; ") +
              "\n\nattempt_completion is BLOCKED. Fix the failures above, call clinerules_validate_completion again, then re-run this check. Do NOT call attempt_completion while this gate is blocked.",
          }],
        };
      }
      return {
        content: [{
          type: "text" as const,
          text: "\u2705 RULE 91 GATE CLEAR\n\nNo gate file at " + gateFile + ". Safe to call attempt_completion.",
        }],
      };
    } catch (e: any) {
      return {
        content: [{
          type: "text" as const,
          text: "\u274c GATE_CHECK_ERROR: could not read gate file " + gateFile + ": " + e.message,
        }],
      };
    }
  }
);

server.tool(
  "clinerules_stats",
  "Quick stats on the rules corpus + recent lookup activity. Used to verify the MCP is healthy and to track adoption.",
  {},
  async () => {
    const corpus = db.prepare(`
      SELECT COUNT(*) AS n, SUM(size_bytes) AS bytes, SUM(size_tokens_est) AS tokens,
             SUM(is_hardfloor) AS hf, SUM(has_source_incident) AS with_src
      FROM rules
    `).get() as any;
    const lookups24 = db.prepare(`
      SELECT COUNT(*) AS n FROM lookups WHERE looked_up_at >= datetime('now','-1 day')
    `).get() as any;
    const violations30 = db.prepare(`
      SELECT COUNT(*) AS n FROM violations WHERE recorded_at >= datetime('now','-30 day')
    `).get() as any;
    const topLookups = db.prepare(`
      SELECT rule_id, COUNT(*) AS n FROM lookups
       WHERE rule_id IS NOT NULL AND looked_up_at >= datetime('now','-7 day')
       GROUP BY rule_id ORDER BY n DESC LIMIT 5
    `).all() as any[];
    const meta = db.prepare(`SELECT * FROM meta`).all() as any[];
    const lines = [
      `clinerules-mcp v${VERSION}`,
      `Corpus: ${corpus.n} rules, ${corpus.bytes} bytes, ~${corpus.tokens} tokens.`,
      `Hardfloor: ${corpus.hf} rules. With source-incident citation: ${corpus.with_src}.`,
      `Lookups last 24h: ${lookups24.n}.`,
      `Violations recorded last 30d: ${violations30.n}.`,
      topLookups.length ? `Top 5 looked-up rules (7d): ${topLookups.map(r => `${r.rule_id}(${r.n})`).join(", ")}` : "No lookups yet.",
      `Meta: ${meta.map((m:any) => `${m.k}=${m.v}`).join(", ")}`,
    ];
    return { content: [{ type: "text", text: lines.join("\n") }] };
  }
);

// ─── Run ───────────────────────────────────────────────────────────────────

(async () => {
  const transport = new StdioServerTransport();
  await server.connect(transport);

  // 2026-05-19 v2 fix (Phase 3 follow-up): do NOT reindex at startup.
  // The SQLite index from the previous run is already populated. Any stale
  // entry will be fixed on the next `clinerules_reindex` tool call or by
  // the background interval below. Cline's MCP initialize timeout is short
  // and any startup work (even 200ms) was racing it.
  const initialCount = (db.prepare(`SELECT COUNT(*) AS n FROM rules`).get() as any)?.n ?? 0;
  console.error(`[clinerules-mcp] v${VERSION} stdio connected · ${initialCount} rules from cached index · ready to serve`);

  // Background reindex every 5 min — but ONLY if a rule file actually changed
  // (2026-07-03 WAL-bloat fix). Previously this blindly deleted + re-inserted
  // all 251 rules every 5 min per process; with 5 concurrent windows that was
  // ~25 reindex-tx/min hammering the shared SQLite WAL.
  setInterval(() => {
    try {
      if (!needsReindex()) return;
      stats = reindex(db, false);
    } catch (e: any) {
      console.error(`[clinerules-mcp] background reindex failed: ${e?.message}`);
    }
  }, 5 * 60 * 1000);

  // One reindex 10s after startup — only if the index is stale (another window
  // may have just reindexed). Always run a passive checkpoint to keep WAL small.
  setTimeout(() => {
    try {
      if (needsReindex()) {
        stats = reindex(db, true);
      } else {
        try { db.pragma("wal_checkpoint(PASSIVE)"); } catch { /* non-fatal */ }
      }
    } catch (e: any) {
      console.error(`[clinerules-mcp] post-startup reindex failed: ${e?.message}`);
    }
  }, 10_000);

  // Orphan guard (2026-07-03): when a Cline window closes, the extension host
  // (our parent) exits and we get reparented to launchd (PPID=1). Without this
  // check, orphaned clinerules processes accumulate — each holding the SQLite
  // DB open and running background reindexes against the shared WAL. Detected
  // 3 such orphans (from 12:24-12:32) still alive at 15:56. Self-exit within
  // 30s of parent death so the DB handle is released.
  setInterval(() => {
    try {
      if (process.ppid === 1) {
        console.error(`[clinerules-mcp] parent process gone (PPID=1), exiting to avoid orphan leak`);
        process.exit(0);
      }
    } catch { /* never crash the server on a guard check */ }
  }, 30_000);
})();
