#!/usr/bin/env bash
#
# sync_hardfloor_manifest.sh — SINGLE SOURCE OF TRUTH for the hardfloor rule set.
#
# Per idea #25151. Root cause it fixes (2026-08-08 RCA):
#   HARDFLOOR_SLUGS was duplicated in FOUR places that had to agree by hand:
#     1. clinerules-mcp/src/index.ts      (the MCP registry)
#     2. Rules/.pre-write-lint.sh          (the G5/G6 write gate)
#     3. Rules/*.md                        (what is actually on disk / auto-loaded)
#     4. /etc/litellm/_router_core.py      (_STEERING_HARDFLOOR_FULL, server side)
#   The 2026-07-25 floor trim updated only some of them. The MCP named 9 rules while
#   20 were on disk, so rules 119/120/143/144/259/267/161/297/99-subagent were being
#   loaded into every window but reported as NOT hardfloor by the registry. Nothing
#   treated them as binding. The divergence survived ~2 weeks undetected.
#
# The durable fix is to stop maintaining copies. This script DERIVES the set from the
# Rules/ directory listing (the only copy that cannot lie, because it IS what Cline
# loads) and writes it to ONE manifest that every consumer reads.
#
# Classification (mechanical, no hand-maintained list):
#   META      = filename starts with '_', OR is in the META_EXTRA list below.
#               Always-loaded, but navigation/auto-generated, not a binding gate.
#   HARDFLOOR = every other *.md in Rules/.
#
# Usage:
#   sync_hardfloor_manifest.sh            # regenerate manifest, report drift
#   sync_hardfloor_manifest.sh --check    # exit 1 if manifest is stale (for audit cron)
#   sync_hardfloor_manifest.sh --quiet    # no stdout unless drift/error
#
set -uo pipefail

RULES_DIR="$HOME/Documents/Cline/Rules"
MANIFEST="$RULES_DIR/.hardfloor-manifest"
MODE="${1:-}"

# Files that are always-loaded but are META (navigation / auto-generated), not gates.
# Anything starting with '_' is auto-detected; this list is only for the ones that don't.
META_EXTRA=("EXECUTE_ORDER_66" "REQUIREMENT_IDEA_AUTO_FILE" "99-yolo-prevention-learned")

is_meta() {
    local slug="$1"
    case "$slug" in _*) return 0 ;; esac
    local m
    for m in "${META_EXTRA[@]}"; do
        [ "$slug" = "$m" ] && return 0
    done
    return 1
}

# --- derive from the directory (the only copy that cannot lie) -----------------
hardfloor=()
meta=()
for f in "$RULES_DIR"/*.md; do
    [ -e "$f" ] || continue
    base=$(basename "$f")
    slug="${base%.md}"
    # skip backups and editor droppings that should never have been in Rules/
    case "$base" in *.bak*|*~|._*) continue ;; esac
    if is_meta "$slug"; then
        meta+=("$slug")
    else
        hardfloor+=("$slug")
    fi
done

NEW_CONTENT=$(
    echo "# GENERATED by sync_hardfloor_manifest.sh — DO NOT HAND-EDIT."
    echo "# Single source of truth for the hardfloor set (idea #25151)."
    echo "# Derived from the Rules/ directory listing. To change the set, add or remove"
    echo "# the .md file in Rules/ and re-run this script. Consumers read THIS file:"
    echo "#   - clinerules-mcp/src/index.ts (loadHardfloorManifest)"
    echo "#   - Rules/.pre-write-lint.sh    (G5 hardfloor gate, G6 non-hardfloor gate)"
    echo "# Regenerated: $(date '+%Y-%m-%dT%H:%M:%S%z')"
    echo "[hardfloor]"
    printf '%s\n' "${hardfloor[@]}" | sort
    echo "[meta]"
    printf '%s\n' "${meta[@]}" | sort
)

OLD_CONTENT=""
[ -f "$MANIFEST" ] && OLD_CONTENT=$(cat "$MANIFEST")

# Compare ignoring the volatile "Regenerated:" timestamp line
strip_ts() { grep -v '^# Regenerated:' <<<"$1"; }

if [ "$(strip_ts "$OLD_CONTENT")" = "$(strip_ts "$NEW_CONTENT")" ]; then
    [ "$MODE" = "--quiet" ] || echo "OK manifest in sync: ${#hardfloor[@]} hardfloor + ${#meta[@]} meta = $(( ${#hardfloor[@]} + ${#meta[@]} )) files"
    exit 0
fi

if [ "$MODE" = "--check" ]; then
    echo "DRIFT manifest is stale vs Rules/ directory listing." >&2
    diff <(strip_ts "$OLD_CONTENT") <(strip_ts "$NEW_CONTENT") >&2
    exit 1
fi

echo "$NEW_CONTENT" > "$MANIFEST"
echo "UPDATED manifest: ${#hardfloor[@]} hardfloor + ${#meta[@]} meta = $(( ${#hardfloor[@]} + ${#meta[@]} )) files"
if [ -n "$OLD_CONTENT" ]; then
    echo "--- changes ---"
    diff <(strip_ts "$OLD_CONTENT") <(strip_ts "$NEW_CONTENT") || true
fi
exit 0
