#!/usr/bin/env node
/**
 * task_index_snapshot.js — idea #19426
 *
 * Durable fix for Cline window loss. Ruben lost the closed-window list 3x in 3 days
 * (2026-07-24, 2026-07-26 twice), each time forcing 30-60 min of forensic parsing of
 * ~60MB of api_conversation_history.json by hand.
 *
 * Writes two artifacts:
 *   ~/Documents/Cline/task_index.json  — machine-readable, full index, mtime-cached
 *   ~/Documents/Cline/OPEN_WINDOWS.md — human/agent-readable, last 72h, with verbatim
 *                                        rule-91 PICKUP PROMPT blocks
 *
 * A fresh Cline window recovering lost work should `read_file OPEN_WINDOWS.md` FIRST.
 * Do NOT re-write a parser.
 *
 * Perf: only re-parses task dirs whose api_conversation_history.json mtime changed
 * since the last run. 2200+ dirs, steady-state run is a few seconds.
 */
const fs = require("fs");
const path = require("path");

const HOME = process.env.HOME;
const TASKS = path.join(HOME, "Library/Application Support/Code/User/globalStorage/saoudrizwan.claude-dev/tasks");
const OUT_JSON = path.join(HOME, "Documents/Cline/task_index.json");
const OUT_MD = path.join(HOME, "Documents/Cline/OPEN_WINDOWS.md");
const RECENT_HOURS = parseInt(process.env.RECENT_HOURS || "72", 10);

const txt = (m) => {
  if (!m) return "";
  if (typeof m.content === "string") return m.content;
  return (m.content || []).map((c) => c.text || "").join("\n");
};

let cache = {};
try { cache = JSON.parse(fs.readFileSync(OUT_JSON, "utf8")).tasks || {}; } catch (e) { cache = {}; }

const index = {};
let parsed = 0, reused = 0, failed = 0;

let dirs = [];
try { dirs = fs.readdirSync(TASKS); } catch (e) {
  console.error("tasks dir unreadable: " + e.message);
  process.exit(1);
}

for (const d of dirs) {
  const conv = path.join(TASKS, d, "api_conversation_history.json");
  let st;
  try { st = fs.statSync(conv); } catch (e) { continue; }
  const mtime = Math.floor(st.mtimeMs);

  if (cache[d] && cache[d].mtime === mtime) {
    index[d] = cache[d];
    reused++;
    continue;
  }

  let a;
  try { a = JSON.parse(fs.readFileSync(conv, "utf8")); } catch (e) { failed++; continue; }

  let title = txt(a.find((m) => m.role === "user"));
  title = title
    .replace(/# task_progress RECOMMENDED[\s\S]*/, "")
    .replace(/<environment_details>[\s\S]*?<\/environment_details>/g, "")
    .replace(/<\/?task>/g, "")
    .trim();

  // last rule-91 pickup prompt block emitted by the assistant
  let pickup = null;
  for (let i = a.length - 1; i >= 0; i--) {
    if (a[i].role !== "assistant") continue;
    const t = txt(a[i]);
    const idx = t.indexOf("PICKUP PROMPT");
    if (idx !== -1) { pickup = t.slice(Math.max(0, idx - 80), idx + 3500); break; }
  }

  // every #NNNN referenced, with bracket tag if one immediately follows
  const ideaMap = {};
  const full = a.map(txt).join("\n");
  const re = /#(\d{4,6})(\s*\[([a-z_:\- ]+)\])?/g;
  let m2;
  while ((m2 = re.exec(full)) !== null) {
    const id = m2[1];
    const tag = m2[3] || null;
    if (!ideaMap[id] || (tag && !ideaMap[id])) ideaMap[id] = tag || ideaMap[id] || null;
  }

  index[d] = {
    task_id: d,
    mtime,
    created_at: new Date(parseInt(d.slice(0, 13), 10)).toISOString(),
    last_modified: new Date(mtime).toISOString(),
    size_kb: Math.round(st.size / 1024),
    turn_count: a.length,
    title: title.slice(0, 700),
    pickup_prompt: pickup,
    ideas: ideaMap,
  };
  parsed++;
}

fs.mkdirSync(path.dirname(OUT_JSON), { recursive: true });
fs.writeFileSync(
  OUT_JSON,
  JSON.stringify({ generated_at: new Date().toISOString(), counts: { parsed, reused, failed, total: Object.keys(index).length }, tasks: index }, null, 1)
);

// ---- markdown render: last RECENT_HOURS by last_modified ----
const cutoff = Date.now() - RECENT_HOURS * 3600 * 1000;
const recent = Object.values(index)
  .filter((t) => t.mtime >= cutoff)
  .sort((a, b) => b.mtime - a.mtime);

const pt = (iso) => new Date(iso).toLocaleString("en-US", { timeZone: "America/Los_Angeles" });

let md = "# OPEN WINDOWS — Cline task snapshot\n\n";
md += "Auto-generated by `~/Documents/Cline/scripts/task_index_snapshot.js` (idea #19426).\n";
md += "Do NOT hand-edit. Regenerated every 30 min by launchd `com.emsu.cline-task-index`.\n\n";
md += "**If you are a fresh window recovering lost work: this file IS the recovery artifact.**\n";
md += "Read it instead of parsing `api_conversation_history.json`. Machine-readable twin: `task_index.json`.\n\n";
md += "Generated: " + pt(new Date().toISOString()) + " PT | window: last " + RECENT_HOURS + "h | ";
md += recent.length + " tasks | index total " + Object.keys(index).length + " (parsed " + parsed + ", cached " + reused + ")\n\n";
md += "| Task ID | Last active (PT) | Turns | Size | Title (first line) |\n|---|---|---|---|---|\n";
for (const t of recent) {
  const firstLine = (t.title.split("\n").find((l) => l.trim()) || "(no title)").slice(0, 90).replace(/\|/g, "\\|");
  md += "| `" + t.task_id + "` | " + pt(t.last_modified) + " | " + t.turn_count + " | " + t.size_kb + "KB | " + firstLine + " |\n";
}
md += "\n---\n\n## Per-window detail\n";
for (const t of recent) {
  md += "\n### `" + t.task_id + "` — " + pt(t.last_modified) + " PT — " + t.turn_count + " turns\n\n";
  md += "**Original task:**\n\n```\n" + t.title.slice(0, 600) + "\n```\n\n";
  const ids = Object.keys(t.ideas).sort();
  if (ids.length) {
    md += "**Ideas referenced:** " + ids.map((i) => "#" + i + (t.ideas[i] ? " [" + t.ideas[i] + "]" : "")).join(", ") + "\n\n";
  }
  if (t.pickup_prompt) {
    md += "**Last PICKUP PROMPT:**\n\n```\n" + t.pickup_prompt + "\n```\n";
  } else {
    md += "_No PICKUP PROMPT found in this window (never completed, or rule-91 violation)._\n";
  }
}
fs.writeFileSync(OUT_MD, md);

console.log("task_index_snapshot: parsed=" + parsed + " cached=" + reused + " failed=" + failed + " total=" + Object.keys(index).length + " recent=" + recent.length);
console.log("  -> " + OUT_JSON);
console.log("  -> " + OUT_MD);
